### ISSUE TITLE
Chapter 4 doesn't mention trouble breathing and coughing up blood explicitly (enough)

### ISSUE THREAD

**Issue by ropg** [covid-at-home/covid-at-home.github.io#27]
title says it all

**Comment by msiflow** [comment]
For this level it‘s a good advice to dispose some dark cloths or towels or even better dark tissues to be disposed for a less  fearful handling of blood.

**Comment by verawilde** [comment]
made mentions more explicit for breathlessness and coughing up blood. 

the incidence of coughing up blood seems to be low (1%) but it seems to be a poor indicator of prognosis. so i think you don't want to hide it on dark cloths or towels, because you want to know/see it for sure... what do people think?

**Comment by msiflow** [comment]
They get More scared.
I agree with you Vera

**Comment by verawilde** [comment]
Thanks much. We don't want people to panic, but... definitely to call for help when they see this, it seems.
