### ISSUE TITLE
dangerous advice

### ISSUE THREAD

**Issue by MichaelKreil** [covid-at-home/covid-at-home.github.io#3]
Wearing a medical mask has no effect on the survival probability of normal people. This is complete nonsense.
But it does affect the likelihood of hospital staff becoming infected because they can no longer get masks and are then no longer able to work and care for critical patients.
In short, the advice to buy these masks is dangerous bullshit.

**Comment by MichaelKreil** [comment]
Christian Drosten:

> Für dieses Tragen von Atemschutzmasken in der normalen Umgebung durch den Normalbürger – da gibt es keine wissenschaftliche Evidenz, dass das irgendeinen Nutzen hat oder irgendeinen Schutz bietet.
> In der jetzigen Situation ist es tatsächlich so, dass es kaum noch Atemschutzmasken zu kaufen gibt. Und wir brauchen diese Atemschutzmasken im Krankenhaus. Im Krankenhaus direkt, also die Krankenschwester, die ständig mit so einem Patienten zu tun hat, die profitiert von einer Atemschutzmaske.
> Die wird sich unter anderem deswegen vielleicht weniger infizieren, wenn so ein Patient sie anhustet. Da gibt es auch kleine Flüssigkeits-Spritzer, die dann abgehalten werden. Wir haben tatsächlich im Moment ein bisschen das Problem, dass wir diese Atemschutzmasken für das medizinische Personal nur noch unter Schwierigkeiten bestellen können.
> Und es macht es natürlich nicht leichter, wenn sich jetzt die gesamte Bevölkerung auch noch denkt, ich kaufe mir das irgendwo im Internet. Denn egal, ob man es im Internet bestellt oder in der Apotheke — es kommt aus demselben Lager.
> Und da muss man schon sagen, man sollte sich jetzt eben nicht in der Bevölkerung mit solchen Atemschutzmasken eindecken. Erstens, weil sie nicht wirken. Zweitens, weil man sie dann da weg kauft, wo sie eigentlich gebraucht werden.

https://www.ndr.de/nachrichten/info/coronaskript102.pdf

**Comment by MichaelKreil** [comment]
Christian Drosten

> Und was dann diese Mundmasken angeht:
> Die brauchen wir für das Virus in einer Krankenhausambulanz oder auch am Krankenbett. Wo Krankenschwestern oder Ärzte ein viel engeren Kontakt mit Patienten haben, nämlich bei Prozeduren, die zum Beispiel Proben–Abnahme aus den Atemwegen umfassen oder auch das Saubermachen von Atemwegen bei intubierten Patienten, da ist es tatsächlich so, das Spritzer auf den Nasen Mundbereich gelangen können. Natürlich müssen im Krankenhaus während der ganzen Arbeitszeit diese Mundmasken getragen werden.
> Und im Moment muss man wirklich befürchten, dass wegen irgendwelcher Hamster– und Vorratskäufe von solchen Atemmasken die Krankenhäuser Probleme kriegen, die noch für die Ärzte und Krankenschwestern zu beschaffen.

https://www.ndr.de/nachrichten/info/coronaskript104.pdf

**Comment by 229c9cf0** [comment]
If you are infected and you must go outside anyway, wearing a mask reduces the likelihood of you infecting other people. (That's why this is standard procedure in Asian countries. Always. Even just for common cold, normal flu, …) With COVID-19, people are infectious while still pre-symptomatic. As such, this is sound advice and not "complete nonsense" or "dangerous bullshit". Wearing a mask can save (other people's) lives.

That western countries messed up keeping a large enough stockpile doesn't change this. Their strategy is now to deny the efficacy of this, redistributing risks and trying to recover from a grave mistake.

Also, just above the part that you're complaining about, there's this:

> Please listen to official advice on what **not** to buy so as to not make things unavailable to the doctors and nurses who need them the most.

So I don't think anything needs to change here.

**Comment by MichaelKreil** [comment]
Ok, I'm quoting Prof. Christian Drosten, the scientist who has been researching corona viruses for 8 years, he is one of the co-discoverers of SARS, and has developed the SARS-CoV-2 test, which is currently being used worldwide and he also advises the German government.
On the other hand, an anonymous hexadecimal number comes from the Internet that has a different opinion.
Thank you for your opinion, but I continue to trust the experts who warn against buying such masks because the resulting supply bottlenecks endanger human lives.

**Comment by ropg** [comment]
Hi Michael, hi 229c9cf0,

Thanks for commenting. We thought about this for a while. There are different norms in different countries when it comes to masks, and indeed in Asia they are much more common, esp. for people with a cough. When people take care of sick people we (and the doctors we asked) think wearing a mask is prudent. It is even mandatory for housemates that come in the same room as the sick person in the [COVID home quarantine protocol](https://lci.rivm.nl/covid-19/bijlage/thuisisolatie) of the Dutch ministry of health and probably in other places as well. 

But I'll see if I can add even more nuance to the text.

More generally, the main assumption behind this website is that over the next few weeks and months, in some places, at some points in time, things will get a little chaotic, and people need to be able to do as much as possible themselves and have compact and well-curated sources of information. Any attempt to get people to prepare for trouble has a built-in tension with the notion that the government is going to take care of everything and will distribute supplies when needed. I have friends who needed to (and had reason to) get tested here in Berlin, and their harrowing story doesn't exactly inspire a ton of confidence. But the government here is ramping things up, we may be impressed just yet.

**Comment by ropg** [comment]
I changed the text, hopefully to your liking.

Also, just FYI: [current WHO advice](https://apps.who.int/iris/bitstream/handle/10665/331133/WHO-nCov-IPC-HomeCare-2020.2-eng.pdf) says both patient and caregiver should wear a mask.

Thing is I understand both the WHO ("patient and caregiver really need masks") and Drosten ("but if they are in short supply let the doctors and nurses have them first"). Truth is we are simply not going to win this war without enough tests or masks. China just pointed at a bunch of factories and said "You, you and you: make masks, lots of them!". They are winning this war, partly because masks are mandatory outside. We will need the same commandeering approach over here, and there is the true scandal. Given that it's standing WHO guidance, may I propose we tone it down from "dangerous advice" and "complete nonsense" and bump elbows in hopes that our governments get their asses in gear?

**Comment by MichaelKreil** [comment]
You wrote:
> "It is even mandatory for housemates that come in the same room as the sick person in the COVID home quarantine protocol of the Dutch ministry of health and probably in other places as well."

Well, let's have a look at that: You link to the dutch "home isolation protocol", that is an appendix to a "[CONCEPT-richtlijn](https://lci.rivm.nl/richtlijnen/covid-19)", that is intended to give a guideline for **GGD and hospitals**. It is **NOT** giving **YOU** the advice to **BUY** medical masks!

On the contrary!
The GGD links on the same page to a [public FAQ](https://www.rivm.nl/coronavirus/covid-19/vragen-antwoorden)
Have a look at question: "Heeft het zin om een mondkapje te dragen om je te beschermen tegen COVID-19?"
> Q: Does it make sense to wear a mouth mask to protect you from COVID-19?
> A: In the Netherlands, we **only recommend mouth masks for medical staff**. People who work with (potentially) infected people …

The same applies to your link to WHO:
> This rapid advice is intended to guide public health and infection prevention and control (IPC) professionals, healthcare managers and healthcare workers (HCWs)

I'm pretty sure that neither you nor the visitors of your page are "**public health and infection prevention and control professionals, healthcare managers and healthcare workers**"!

And what do the [WHO FAQ](https://www.who.int/news-room/q-a-detail/q-a-coronaviruses) tell us?
> Q: Should I wear a mask to protect myself?
> A: … If you are not ill or looking after someone who is ill then you are wasting a mask. **There is a world-wide shortage of masks, so WHO urges people to use masks wisely.**

To me this sounds exactly like the opposite of "Everyone should put masks on their shopping list".
So basically you are making the "world-wide shortage of masks" even worse, while medical personnel urgently need them.
And that's why your advice is dangerous!

**Comment by ropg** [comment]
When I read my text, I see

>Then there’s the fact that some people have been panic-buying and some companies have been price-gouging, making essential equipment like masks unavailable in some places even to doctors and nurses who really need them. If it’s still early in the pandemic, your government may be providing masks to people who live with and/or care for people with COVID-19. The section here describes things that you could try to get if you need to be caring for other people.
> Please listen to official advice on what not to buy so as to not make things unavailable to the doctors and nurses who need them the most. Policies and general practice with regard to masks are going to vary wildly across the world for a while to come. Going outside with a mask or wearing one in regular daily life may make only limited sense you’re healthy. (Which also means you don’t need a ton of masks.) But it probably makes sense to wear a mask if you feel a little ill or are coughing. It also makes sense if you are taking care of someone who is sick. It is even mandatory in the COVID quarantine home care protocols in some countries. See the main text about further things to think about when it comes to containing the spread of the virus as much as possible.
> When it comes right down to it you’ll have to make your own choices as to the level of protection that is appropriate in your situation.

I see a very balanced text that acknowledges the tightrope and does in no way say:

> "Everyone should put masks on their shopping list"


The Chinese found that their biggest problem was transmission in the home, which is why they either did not allow home quarantine or made very sure everyone around the patient took precautions, which very much included masks. Our text is specifically made to be applicable in many different countries and situations. If I had an elderly mother with COPD to take care of right now, I would make sure I had some masks in case I would develop a cough. And so would you, I might imagine.

Can I switch the topic for a moment? I'd honestly like your opinion on the rest of the site and the information on it.

**Comment by MichaelKreil** [comment]
> On Tuesday, the head of the Association of Statutory Health Insurance Physicians, Walter Plassmann, sounded the alarm. "**We have been desperately trying for weeks to buy protective equipment somewhere in the world, it is almost impossible**", the "Doctors' Intelligence Service" quoted him as saying. Weeks ago, the Federal Government would have promised to help them. So far, however, without result. "Nothing has come of it. We did not get a single mask," said Plassmann. But it must be clear to everyone: "**If we run out of protective equipment, we are finished**".
> The medical staff is not only exposed to a particularly high risk of infection and falls out if they fall ill. **If doctors and nurses are insufficiently protected, the risk of transmitting viruses and other germs to people who are already ill and weakened increases, causing them massive damage. If the upcoming deliveries do not arrive, the supplies in Hamburg will run out over the weekend**, Plassmann said.
https://www.spiegel.de/wissenschaft/medizin/corona-krise-hersteller-von-schutzkleidung-greift-jens-spahn-an-a-dba397bb-d86b-4779-af8c-1912aebce7ac

Our society is currently heading for a catastrophe that we can only prevent as a society.
Your advice doesn't help society, it only helps paranoid egotists.
I would like you to go through every single point of your recommendations and check whether this recommendation improves or worsens the epidemic if 30 million households in Germany follow your advice.
"Buy masks, screw doctors" is a great example of an asshole recommendation.
"How to make your own DIY masks" is a great example of a sensible recommendation that benefits society.

**Comment by ropg** [comment]
I just simply cannot see, even in the previous version, which made it **very** clear that in some countries you should not buy masks, you read "Buy masks, screw doctors" when in fact it said "Please listen to official advice on what not to buy so as to not make things unavailable to the doctors and nurses who need them the most."

However, I have made the text stronger still on all versions, and stronger still on the german one. It now says **Aber bitte höre unbedingt auf offizielle Anweisungen, was nicht gekauft werden sollte, damit die Dinge nicht für die Ärzte und Krankenschwestern, die sie am meisten brauchen, unerreichbar werden** in bold print.

This website is for an international audience and focuses on people caring for actual COVID patients, not people that feel scared walking down the street. Masks exist, and we cannot make a website about care for patients and pretend they don't. 

Can you please go bother the 100 sites/videos that talk about masks without mentioning anything we did? We're busy... I'm closing the issue. Not because I feel we couldn't go back and forth for another ten times, but because I cannot help but feel that you're not really reading what we write.

I'm still curious what you think of the site in general though: I generally learn most from people that are critical of what I do.

**Comment by ropg** [comment]
(Oh and I like the DIY mask idea, that's going in... As soon as someone has a minute... URLs?)

**Comment by MichaelKreil** [comment]
> … very clear that in some countries you should not buy mask

WTF!
What part of "global shortage" do you not understand? Is it the aspect that this shortage is global, that hospitals are in panic, that surgeons need masks to do surgery, that there have been warnings about it for several weeks or that it affects all countries?

UK: https://www.theguardian.com/society/2020/mar/16/not-fit-for-purpose-uk-medics-condemn-covid-19-protection
USA: https://www.nytimes.com/2020/03/09/health/coronavirus-n95-face-masks.html
France: https://www.lemonde.fr/planete/article/2020/03/16/le-manque-de-masques-fleau-recurrent-des-medecins_6033238_3244.html
Spain: https://cnnespanol.cnn.com/video/coronavirus-brote-escasez-de-mascarillas-guantes-insumos-medicos-pkg-portafolio-global-cnnee/
Netherland: https://www.trouw.nl/binnenland/grootste-zorg-van-ziekenhuizen-misschien-wel-het-dreigend-tekort-aan-mondkapjes~b2a5363b/
Germany: https://www.welt.de/wirtschaft/article206109105/Coronavirus-Atemschutzmasken-fast-ausverkauft.html

Ok, to make my point absolutely clear:

Hospitals are in panic, because there is a global shortage of medical masks ... and the pandemic has not even really started yet.
There is a global shortage, because some stupid assholes are panic buying them.
You recommend that the general public should buy medical masks.
You are a stupid asshole.

**Comment by 229c9cf0** [comment]
It looks like [A Significant Portion of COVID-19 Transmission Is Presymptomatic](https://www.lesswrong.com/posts/9GyKccaJdLEbdhyTi/a-significant-portion-of-covid-19-transmission-is) so to not accidentally infect others before you know you're infected, https://wearafuckingmask.com/  – [it](https://www.sciencedirect.com/science/article/pii/S2211335516301553) [actually](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2440799/) [helps](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3306645/)!

And because we have known for a long time that [there will be shortages](https://academic.oup.com/annweh/article/54/7/789/202744) in case of a [pandemic](http://resiliencemaps.org/files/fluscim/FluSCIM-69p-English.pdf) (because it's cheaper not to prepare and then blame others afterwards), you will have to [make your own masks](https://diymask.site/) until production ramps up, even that is ["better than nothing"](https://www.reuters.com/article/us-health-coronavirus-thailand-masks-idUSKBN20Z0UT). 

-----

Calling people assholes doesn't exactly improve your chances of convincing them, seems it's still a standard behavior in normie logic.
